format = """
$username\
$hostname\
$env_var\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$character"""

[git_branch]
style="fg:#a67bf5"

[username]
disabled = false
format = "[$user]($style) at "

[gcloud]
disabled = true

[git_state]
disabled = true
style="fg:green"

[git_status]
disabled = true
style="fg:#a67bf5"
stashed = 'S'
deleted = 'D'

[hostname]
style = "fg:15"
ssh_only = true
disabled = false
format = "[$hostname]($style) "

[directory]
style="fg:12 bold"
truncate_to_repo = false
truncation_length = 2
fish_style_pwd_dir_length = 1
format = "in [$path]($style)[$read_only]($read_only_style) "


[ruby]
symbol = "ruby "

[golang]
symbol = "go "

[python]
disabled = true

[java]
disabled = true

[env_var]
variable = "shell_via"
format = "via [$env_value]($style) "
style="green"
