function hame-vim

    set -l vim .vim/pack/dylan
    hame-git $HAME_FLAGS -n  solarized8        -p "$vim/opt/solarized8"          -u  "lifepillar/vim-solarized8"
    hame-git $HAME_FLAGS -n  abolish           -p "$vim/start/abolish"           -u  "tpope/vim-abolish"
    hame-git $HAME_FLAGS -n  ag                -p "$vim/start/ag"                -u  "epmatsw/ag.vim"
    hame-git $HAME_FLAGS -n  airline           -p "$vim/start/airline"           -u  "vim-airline/vim-airline"
    hame-git $HAME_FLAGS -n  airline-themes    -p "$vim/start/airline-themes"    -u  "vim-airline/vim-airline-themes"
    hame-git $HAME_FLAGS -n  commentary        -p "$vim/start/commentary"        -u  "tpope/vim-commentary"
    hame-git $HAME_FLAGS -n  cpanfile          -p "$vim/start/cpanfile"          -u  "moznion/vim-cpanfile"
    hame-git $HAME_FLAGS -n  endwise           -p "$vim/start/endwise"           -u  "tpope/vim-endwise"
    hame-git $HAME_FLAGS -n  eunuch            -p "$vim/start/eunuch"            -u  "tpope/vim-eunuch"
    hame-git $HAME_FLAGS -n  fish              -p "$vim/start/fish"              -u  "dag/vim-fish"
    hame-git $HAME_FLAGS -n  fugitive          -p "$vim/start/fugitive"          -u  "tpope/vim-fugitive"
    hame-git $HAME_FLAGS -n  gitgutter         -p "$vim/start/gitgutter"         -u  "airblade/vim-gitgutter"
    hame-git $HAME_FLAGS -n  html5             -p "$vim/start/html5"             -u  "othree/html5.vim"
    hame-git $HAME_FLAGS -n  perl              -p "$vim/start/perl"              -u  "vim-perl/vim-perl"
    hame-git $HAME_FLAGS -n  racket            -p "$vim/start/racket"            -u  "wlangstroth/vim-racket"
    hame-git $HAME_FLAGS -n  rails             -p "$vim/start/rails"             -u  "tpope/vim-rails"
    hame-git $HAME_FLAGS -n  repeat            -p "$vim/start/repeat"            -u  "tpope/vim-repeat"
    hame-git $HAME_FLAGS -n  supertab          -p "$vim/start/supertab"          -u  "ervandew/supertab"
    hame-git $HAME_FLAGS -n  surround          -p "$vim/start/surround"          -u  "tpope/vim-surround"
    hame-git $HAME_FLAGS -n  syntastic         -p "$vim/start/syntastic"         -u  "vim-syntastic/syntastic"
    hame-git $HAME_FLAGS -n  tabular           -p "$vim/start/tabular"           -u  "godlygeek/tabular"
    hame-git $HAME_FLAGS -n  textobj-rubyblock -p "$vim/start/textobj-rubyblock" -u  "nelstrom/vim-textobj-rubyblock"
    hame-git $HAME_FLAGS -n  textobj-user      -p "$vim/start/textobj-user"      -u  "kana/vim-textobj-user"
    hame-git $HAME_FLAGS -n  unimpaired        -p "$vim/start/unimpaired"        -u  "tpope/vim-unimpaired"
    hame-git $HAME_FLAGS -n  vinegar           -p "$vim/start/vinegar"           -u  "tpope/vim-vinegar"
end

