abbr -a -U -- d docker
abbr -a -U -- frc 'et /Users/dylan/.config/fish/config.fish'
abbr -a -U -- gap 'git add -p'
abbr -a -U -- gco 'git checkout'
abbr -a -U -- gd 'git diff'
abbr -a -U -- gdc 'git diff --cached'
abbr -a -U -- gis 'git status --short'
abbr -a -U -- gr 'git rebase'
abbr -a -U -- lofn 'env MOSH_TITLE_NOPREFIX=1 mosh lofn'
abbr -a -U -- pt 'perltidy --profile=.perltidyrc -b  -bext=/'
abbr -a -U -- runti 'docker run --rm -ti'
