#!/bin/zsh

desktop_image="$HOME/var/pics/background/$(hostname -s).jpg"
desktop_color=('#000033' '#000033')
desktop_width=1600

keyboard_delay=200
keyboard_rate=30

xset +fp /usr/share/fonts/local
xset fp rehash
xset r rate $keyboard_delay $keyboard_rate

xrdb-reload
xsetroot -cursor_name left_ptr
setxkbmap -option terminate:ctrl_alt_bksp \
	      -option altwin:swap_alt_win \
		  -option ctrl:nocaps

feh --bg-center $desktop_image
parcellite &
batti &
xmonad-bar &
blueman-applet &
