#!zsh

local RESET="%{$reset_color%}"
local YELLOW="%{${fg[yellow]}%}"
local GREEN="%{${fg[green]}%}"
local MAGENTA="%{${fg[magenta]}%}"
local BOLD_GREEN="%{${fg_bold[green]}%}"
local RED="%{${fg[red]}%}"
local GREY="%{${fg_bold[grey]}%}"
local BLUE="%{${fg[blue]}%}"
local BOLD_BLUE="%{${fg_bold[blue]}%}"

PR_TIME="$YELLOW%D{%H:%M}$RESET"
PR_DATE="$YELLOW%D{%Y-%m-%d}$RESET"
PR_DIR="$BOLD_BLUE%~$RESET"
PR_NAME="$BOLD_GREEN%n$RESET"
PR_HOST="$BOLD_GREEN%m$RESET"
PR_JOBS="%2(j.($MAGENTA%j jobs$RESET).%1(j.($MAGENTA%j job$RESET).))"
PR_VCS='${vcs_info_msg_0_}'

autoload -Uz vcs_info ztitle
zstyle ':vcs_info:*' enable svn svk git
zstyle ':vcs_info:*' actionformats \
    '(%F{2}%s:%b, %a%f)'
zstyle ':vcs_info:*' formats       \
    '(%F{2}%s:%b%f)'
zstyle ':vcs_info:(sv[nk]|bzr):*' branchformat '%b:%r'
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:svn:*' check-for-changes true

PROMPT="$PR_TIME $PR_NAME@$PR_HOST:$PR_DIR%# "
PS2='%_: '
RPS2=''

if vcs_info &>/dev/null; then
    precmd_functions+=( vcs_info ztitle )
    RPROMPT="$PR_VCS$PR_JOBS"
else
    RPROMPT="$PR_JOBS"
fi

alias norp='unset RPROMPT'

prompt_opts=( cr percent subst )
