#!zsh

local RESET="%{$reset_color%}"
local YELLOW="%{${fg[yellow]}%}"
local GREEN="%{${fg[green]}%}"
local MAGENTA="%{${fg[magenta]}%}"
local BOLD_GREEN="%{${fg_bold[green]}%}"
local RED="%{${fg[red]}%}"
local GREY="%{${fg_bold[grey]}%}"
local BLUE="%{${fg[blue]}%}"
local BOLD_BLUE="%{${fg_bold[blue]}%}"

local PR_TIME="$YELLOW%D{%H:%M}$RESET"
local PR_DATE="$YELLOW%D{%b-%d}$RESET"
local PR_DIR="$BOLD_BLUE%~$RESET"
local PR_NAME="$BOLD_GREEN%n"
local PR_HOST="%m$RESET"
local PR_JOBS="%2(j.($MAGENTA%j jobs$RESET) .%1(j.($MAGENTA%j job$RESET) .))"
local PR_BRANCH="%1(V. ($GREEN%1v$RESET).)"

function prompt_dylan_chpwd {
	local branch=$(git branch 2>/dev/null | sed -n 's/^\* \(.*\)/\1/p')
	psvar[1]=$branch
}

echo "pants"
prompt_dylan_chpwd 
echo "nopants"
chpwd_functions=( prompt_dylan_chpwd )

PROMPT="$PR_NAME@$PR_HOST:$PR_DIR$PR_BRANCH%# "
RPROMPT="$PR_JOBS$PR_TIME $PR_DATE"
PS2='%_: '
RPS2=''

prompt_opts=( cr percent )
