#!zsh

local RESET="%{$reset_color%}"
local YELLOW="%{${fg[yellow]}%}"
local GREEN="%{${fg[green]}%}"
local MAGENTA="%{${fg[magenta]}%}"
local BOLD_GREEN="%{${fg_bold[green]}%}"
local RED="%{${fg[red]}%}"
local GREY="%{${fg_bold[grey]}%}"
local BLUE="%{${fg[blue]}%}"
local BOLD_BLUE="%{${fg_bold[blue]}%}"

PR_TIME="$YELLOW%D{%H:%M}$RESET"
PR_DATE="$YELLOW%D{%b-%d}$RESET"
PR_DIR="$BOLD_BLUE%~$RESET"
PR_NAME="$BOLD_GREEN%n$RESET"
PR_HOST="$BOLD_GREEN%m$RESET"
PR_JOBS="%2(j.($MAGENTA%j jobs$RESET).%1(j.($MAGENTA%j job$RESET).))"
PR_BRANCH="%1(v. ($GREEN%1v$RESET).)"

function prompt_dylan_precmd {
    local branch=$(git branch 2>/dev/null | awk '{print $2}' )
    if [[ -n $branch ]]; then
        psvar[1]="$branch"
    else
        psvar=()
    fi
}

function notime {
    RPROMPT="$PR_JOBS"
}

prompt_dylan_precmd 
precmd_functions=( $precmd_functions prompt_dylan_precmd )

PROMPT="$PR_NAME@$PR_HOST:$PR_DIR$PR_BRANCH%# "
RPROMPT="$PR_JOBS $PR_TIME $PR_DATE"
PS2='%_: '
RPS2=''

prompt_opts=( cr percent )
