#!zsh
local file=$SSH_AGENT_FILE
if [[ -e $file ]]; then
	source $file &>/dev/null
	if ps aux | awk '/ssh-agent/ { print $2 }' | grep $SSH_AGENT_PID &>/dev/null
	then
		print "ssh-agent: running"
		return
	fi
fi
echo "ssh-agent: starting"
ssh-agent >! $file
chmod 600 $file
source $file &>/dev/null
ssh-add
