#!/bin/zsh
# vim: set ft=zsh:

if [[ -z $1 ]]; then
	echo "usage: perlbrew-install some-dir" >&2
	return 1
fi

export PERLBREW_HOME=${1:a}
export PERLBREW_ROOT=${1:a}
unset PERLBREW_PATH

[[ ! -d $PERLBREW_HOME ]] && perlbrew init

[[ -f $PERLBREW_HOME/etc/bashrc ]] && source $PERLBREW_HOME/etc/bashrc

return 0
