#!zsh

autoload url_decode

local name=info

while getopts 'n:' opt; do
	case $opt in
		n) name=$OPTARG ;;
	esac
done

declare -Ag $name
nyxmms2 info $argv[$OPTIND,$#argv] | while read module key eq val; do
	typeset -g "$name""[$key]"=$val
done

local file="$(eval "url_decode \${${name}[url]}")"
typeset -g "$name""[file]"="${file/file:\/\//}"
