abbr -a -U -- ag rg
abbr -a -U -- ci 'git commit'
abbr -a -U -- gap 'git add -p'
abbr -a -U -- gco 'git checkout'
abbr -a -U -- gdc 'git diff --cached'
abbr -a -U -- gr 'git rebase'
abbr -a -U -- gs 'git status --short'
abbr -a -U -- pt 'perltidy --profile=.../.perltidyrc -b  -bext=/'
abbr -a -U -- pull 'git pull'
abbr -a -U -- push 'git push'
abbr -a -U -- runti 'docker run --rm -ti'
